export default {
	FETCH_TICKETS_REQUEST: 'FETCH_TICKETS_REQUEST',
	FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
	FETCH_TICKETS_FAILURE: 'FETCH_TICKETS_FAILURE',

	FETCH_EXCHANGERATES_REQUEST: 'FETCH_EXCHANGERATES_REQUEST',
	FETCH_EXCHANGERATES_SUCCESS: 'FETCH_EXCHANGERATES_SUCCESS',
	FETCH_EXCHANGERATES_FAILURE: 'FETCH_EXCHANGERATES_FAILURE',

	CHANGE_CURRENCY:    'CHANGE_CURRENCY',
	SET_TICKETS_FILTER: 'SET_TICKETS_FILTER',
};









