export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';

export const FETCH_EXCHANGERATES_REQUEST = 'FETCH_EXCHANGERATES_REQUEST';
export const FETCH_EXCHANGERATES_SUCCESS = 'FETCH_EXCHANGERATES_SUCCESS';
export const FETCH_EXCHANGERATES_FAILURE = 'FETCH_EXCHANGERATES_FAILURE';

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const SET_TICKETS_FILTER = 'SET_TICKETS_FILTER';
